@ParkingLotApi_HostAddress = http://localhost:8080

GET {{ParkingLotApi_HostAddress}}/api/user/pagenumber=1&pageSize=10
Accept: application/json

###

###GET {{ParkingLotApi_HostAddress}}/api/user/1
###Accept: application/json

###
